### ISSUE TITLE
The T&C text is quite small and hard to read, and the zoom is a bit awkward

### ISSUE THREAD

**Issue by AlexCornforth** [Greenstand/treetracker-ios#107]

**Comment by AlexCornforth** [comment]
@rmh211 I'm not so sure what we can do about this but if you wanted to investigate and see if theres any way we can tidy up this screen and make it more user friendly it would be super helpful.

**Comment by rmh211** [comment]
I'll look at it.

**Comment by rmh211** [comment]
I was able to make a change to the sizing. Not sure exactly what to do with the zoom. The pan/scrolling is a challenging, but I’m not sure there is a better UX option. 
![Uploading D8B14E0B-A573-4E2B-9F64-8306202072FA.png…]()

**Comment by rmh211** [comment]
![16CF9C42-F9A4-4F98-90E8-B9647694AF25](https://user-images.githubusercontent.com/69368645/188943947-dde1590f-67fe-497a-8299-1da00ea7ba51.png)

**Comment by rmh211** [comment]
I was able to make the text size better fit to the device screen. The current zoom function is probably still the best implementation from a UX perspective.
