### ISSUE TITLE
Add version number to the settings screen

### ISSUE THREAD

**Issue by AlexCornforth** [Greenstand/treetracker-ios#109]
To help debug issues it will be useful to know which version of the app the bug reports are coming from.

So users can find out let's add the app version and build number to the bottom of the settings screen like so:

<img src="https://user-images.githubusercontent.com/3583566/189132248-de0cc862-7534-4d3f-a36a-9253250b24b0.png" height="500">

Solution Guidence:
- Suggest Lato Regular size 14 for the font
- To acces the version number `Bundle.main.infoDictionary?["CFBundleShortVersionString"]`
- To acces the build number `Bundle.main.infoDictionary?["CFBundleVersion"]`

**Comment by rmh211** [comment]
Alex, I can do this if you would like.

**Comment by vasilinich11** [comment]
I'm ready to work

**Comment by frehelfer** [comment]
I've done the PR right now

**Comment by pranavkparti** [comment]
This issue is resolved and needs to be closed.
