### ISSUE TITLE
Photo quality Settings not reset after delete account

### ISSUE THREAD

**Issue by ramonfe** [Greenstand/treetracker-ios#110]
After account is deleted and create a new one, photo quality remains high as the deleted account-by default is Medium

![image](https://user-images.githubusercontent.com/8714884/189770056-22dbe6ac-7efe-4bb2-8b0d-56c655f75442.png)

**Comment by rmh211** [comment]
Solution Guidance:

Delete Account is not yet implemented in Version 2
To access the settings for photo quality you have to use settingsService and use the .update method
When the account is deleted, this should be updated to the default
