### ISSUE TITLE
Extra character added to email on keyboard suggestion

### ISSUE THREAD

**Issue by ramonfe** [Greenstand/treetracker-ios#111]
On login when I use the keyboard autocomplete suggestion, email is not copied correctly, some extra characters are added to beginning

![image](https://user-images.githubusercontent.com/8714884/189770801-0df7b81f-fc3d-4cf6-8217-d3e964f1d109.png)

**Comment by rmh211** [comment]
I can't seem to replicate this error

**Comment by ramonfe** [comment]
Hope that this can clarify it more.

https://user-images.githubusercontent.com/8714884/189991653-91ded5e6-50dc-4d0d-b619-f5ed344fbdb4.mov

**Comment by rmh211** [comment]
Ok, thank you. That does help.

**Comment by frehelfer** [comment]
This issue can be closed, it was already merged.
