### ISSUE TITLE
Login - text field not cleared 

### ISSUE THREAD

**Issue by ramonfe** [Greenstand/treetracker-ios#112]
On login, when I switch from buttons phone to email, text field is not cleared(not sure if this is a bug)

![image](https://user-images.githubusercontent.com/8714884/189771336-3ea89aa5-14f2-4ce0-99f2-47a37497eef3.png)

**Comment by rmh211** [comment]
I can fix this.

**Comment by rmh211** [comment]
Solution Guidance: (Might be a good early issue to address.)
 - SignInViewController has a method as the ViewModel Delegate:
       signInViewModel(_ signInViewModel: SignInViewModel, didUpdateLoginType loginType: SignInViewModel.LoginType)
- A good place to consider resolving this behavior.
