### ISSUE TITLE
Create the tree list screen

### ISSUE THREAD

**Issue by AlexCornforth** [Greenstand/treetracker-ios#17]
_As a user, I want to see a list of my tree captures, so that I can view my trees and check what is uploaded._

**Acceptance criteria:**
- When I tap on the tree count area of the home screen, does the tree list appear?
- When I open the tree list, can I see my tree captures?
- Is the tree capture list sorted by date?
- On each tree capture can I view the image, capture date and upload status.

**Out of scope**
- Selecting a tree capture to view further detail
- Triggering uploads
- Modifying tree capture data

**Considerations**
The UI design of the app is still being worked on and is likely to change therefore a fancy/polished UI is not necessary at this point. It is more important to get the functionality working at this stage.

**Comment by remivar** [comment]
I don't have the access to assign the issue. @AlexCornforth  can you please assign to myself

**Comment by frehelfer** [comment]
I'll do it!

**Comment by AlexCornforth** [comment]
Closing this issue as not needed and is covered by messaging. We also delete photos so can;t really build this feature
