### ISSUE TITLE
Add selfie photo to home screen

### ISSUE THREAD

**Issue by AlexCornforth** [Greenstand/treetracker-ios#21]
_As a user, I want to see my selfie photo on the home screen, so I know who I am logged in as_

**Acceptance Criteria**
- When I log in to the app, do I see my selfie photo in the navigation bar at the top of the screen

**Out of Scope**
- Selecting the selfie icon to bring up a profile screen

**Solution Guidance**
- The profile image path can be accessed via the planter in HomeViewModel
- The DocumentManager can be used to fetch the image data for the image path
- Use the navigation item leftBarButtonItem e.g.
```
let selfiePhotoButton = UIBarButtonItem(
    image: Asset.Assets.person.image,
    style: .plain,
    target: nil,
    action: nil
)
navigationItem.leftBarButtonItem = selfiePhotoButton
```

**Comment by AlexCornforth** [comment]
@estherswong

**Comment by estherswong** [comment]
Hey @AlexCornforth, could you assign me to this issue?
