### ISSUE TITLE
Create profile screen

### ISSUE THREAD

**Issue by AlexCornforth** [Greenstand/treetracker-ios#22]
_As a user, I want to view my profile information, so that I can check my details_

**Acceptance Criteria**
When I tap on the profile image button, does the profile screen get presented
When I open the profile screen, can I see my selfie image
When I open the profile screen, can I see my name
When I open the profile screen, can I see my email or phone number
When I open the profile screen, can I see my organisation (if applicable)
When I open the profile screen, and press change user, do i return to the login screen.

**Out of Scope**
- Editing a users profile information

**Solution Guidance**
Use HomeCoordinator for navigation logic
Pass the Planter object to the ProfileViewModel from the coordinator - this object should have everything you need.
Create a ProfileViewModel for handling profile screen business logic

**Design Guidance**
Design could change but use this as a guide:

<img src="https://user-images.githubusercontent.com/3583566/109876329-9188bd00-7c69-11eb-9722-f3345af7b7da.png" height="500">

**Comment by AlexCornforth** [comment]
Depends on https://github.com/Greenstand/treetracker-ios/issues/21

**Comment by tjb** [comment]
Hey @AlexCornforth I'd like to tackle this if possible!

**Comment by remivar** [comment]
@AlexCornforth  please assign the ticket to me so that I can start working on this.

**Comment by remivar** [comment]
thank you

**Comment by remivar** [comment]
I started working on the build. created the front end UI using storyboard.
