### ISSUE TITLE
Add logout functionality

### ISSUE THREAD

**Issue by AlexCornforth** [Greenstand/treetracker-ios#23]
_As a user, I want to log out of the app, so that another user can sign in_

**Acceptance Criteria**
When I view the profile screen, is the logout button present
When I tap the logout button, do I get logged out of the app and returned to the sign-in screen

**Solution Guidance** 
Use coordinators for navigation logic

**Comment by AlexCornforth** [comment]
Depends on https://github.com/Greenstand/treetracker-ios/issues/22

**Comment by Maxime-Oriol** [comment]
Ok, I can work on :)
