### ISSUE TITLE
Persist logged in user for up to 2 hours.

### ISSUE THREAD

**Issue by AlexCornforth** [Greenstand/treetracker-ios#28]
_As a user, I want to stay logged in between app launches, so that I don't have to keep logging back in_

**Acceptance Criteria**

- If I am logged in to the app, and I force quit the app for **less** than 2 hours, am I still **logged in** when I relaunch the app
- If I am logged in to the app, and I force quit the app for **more** than 2 hours, am I **logged out** when I relaunch the app
- If I am logged in to the app, press the log out button on the home screen, and then force quit the app for **less** than 2 hours, am I **logged out** when I relaunch the app
- If I am logged in to the app, and I background the app for **more** than 2 hours, am I **logged out** when I reopen the app

**Solution Guidance**
Flow diagram:
![2 Hour Log out](https://user-images.githubusercontent.com/3583566/94455277-c8364500-01aa-11eb-8179-5c21e6ce7e63.png)

Maybe we could persist current user ID along with last login time in user defaults?

**Comment by Maxime-Oriol** [comment]
Sounds good for me, I can do it
