### ISSUE TITLE
Custom camera overlay containing location accuracy

### ISSUE THREAD

**Issue by AlexCornforth** [Greenstand/treetracker-ios#29]
_As a user, I want a custom camera overlay, so that I can add trees quicker_

**Acceptance Criteria**
When I select add tree from the home screen, does the take photo screen appear
Does the take photo screen contain a camera viewport
Does the take photo screen contain the GPS accuracy
Can I only take a photo if my GPS accuracy is 'good'

**Solution Guidence**
Functionality to add a tree already exists but it needs streamlining. 
Could utilise the AddTreeViewController, AddTreeViewModel and GPSAccuracyLabel 
Take a look at the Apple Docs for camera overlay: https://developer.apple.com/documentation/uikit/uiimagepickercontroller/1619113-cameraoverlayview

**Comment by remivar** [comment]
Do we need to work on this feature

**Comment by MonzerMahmoud** [comment]
I will help in it

**Comment by remivar** [comment]
@AlexCornforth  am interested to work on this issue. If no-one is currently working, please assign me

**Comment by remivar** [comment]
@AlexCornforth  thanks a lot. I will use this chance

**Comment by AlexCornforth** [comment]
Completed in PR 106
