### ISSUE TITLE
As a user, I want the signup process to remove spaces from my phone number, so that I can use autofill and not worry about the spaces.

### ISSUE THREAD

**Issue by AlexCornforth** [Greenstand/treetracker-ios#33]
_As a user, I want the signup process to remove spaces from my phone number, so that I can use autofill and not worry about the spaces._

**Acceptance Criteria**
If I use the operating system autofill in the sign up process, are space characters removed before persisting to the database.

**Tests**
On the login screen enter a phone number with spaces (physical keyboard / autofill suggestion / copy paste)
Sign up the user
Log out
Sign back in with the same phone number but without spaces
You should log back in to the user you have just created

**Comment by remivar** [comment]
you can assign me, I will work on this issue

**Comment by remivar** [comment]
@AlexCornforth you can assign me, I will work on this issue

**Comment by remivar** [comment]
thank you @AlexCornforth
