### ISSUE TITLE
Change upload button titles

### ISSUE THREAD

**Issue by AlexCornforth** [Greenstand/treetracker-ios#61]
Change upload button titles from:
"START UPLOADS" to "START UPLOAD"
"STOP UPLOADS" to "STOP UPLOAD"

Text should be changed in the Localizable.strings files and the project rebuilt so swiftgen can regenerate the Strings.swift files (the comments in Strings.swift include the string value)

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue. Please assign me this issue.

**Comment by AlexCornforth** [comment]
Hi @himanshu007-creator 👋 Thanks for wanting to pick this up! If you're interested in contributing please fill out the [contributing form](https://greenstand.org/contribute) on our website.

**Comment by himanshu007-creator** [comment]
> Hi @himanshu007-creator 👋 Thanks for wanting to pick this up! If you're interested in contributing please fill out the [contributing form](https://greenstand.org/contribute) on our website.

done!
