### ISSUE TITLE
Resize image before uploading

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-ios#83]
Images are not resized and arrive at 9MB see https://map.treetracker.org/?treeid=1707079

**https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.12.18.19.42.49_-19.15926153683096_47.591846729775696_CEF49D2D-FD04-4E91-B060-656704AD51D9_A8D03A54-37F6-48A4-88E6-915DB334C358.jpg**

That is a lot of MB for a small tree ;-)

**Comment by AlexCornforth** [comment]
Now limits to ~500px
