### ISSUE TITLE
As a user, I want to add a note to my tree capture, so that I can provide more context

### ISSUE THREAD

**Issue by AlexCornforth** [Greenstand/treetracker-ios#95]
_As a user, I want to add a note to my tree capture, so that I can provide more context_

*Acceptance Criteria*
Once I take  picture of a tree 
And before I save the tree
I can optionally add a note about the tree

*Solution Guidence*
Add a new button to the add tree screen with the title "Note" and maybe some kind of pen icon
This button should only appear once we have a photo
Tapping it should present a view controller in which the user can type a note
A note is optional it should not be required to save the tree
Hold onto the note content in the viewmodel ready to be saved when the save button is pressed
Pass this to the TreeService on save

**Comment by vasilinich11** [comment]
Hey, Alex. I'm ready to work.
